short_reads_1:
    none
short_reads_2:
    none
long_reads:
    none
n_cores:
    8
max_memory:
    64
output:
    none
sequencer_source:
    TruSeq3
workflow:
    process
skip_qc:
    false
assembly_type:
    none
min_read_aligned_percent:
    97
min_read_percent_identity:
    99
singlem_db:
    /work/microbiome/db/uhgg_v2/uhgg.sdb
genome_db:
    /work/microbiome/db/uhgg_v2/genomeID_lineage_fna-list.txt
