from snakemake.utils import min_version
min_version("6.5.3")

if config["workflow"] == "process":
    module process:
        snakefile: "process/Snakefile"
        config: config

    use rule * from process as *

elif config["workflow"] == "mapper":
    module mapper:
        snakefile: "mapper/Snakefile"
        config: config

    use rule * from mapper as *

else:
	print('Specify a workflow')
